export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const SET_LIKE = 'SET_LIKE';
export const SET_DISLIKE = 'SET_DISLIKE';
